services:
  db:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      POSTGRES_DB: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

# If you have more than one container and want them to communicate through
# same network
networks:
  db:
    driver: bridge

volumes:
  db: